[package]
name = "pre-commit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
dirs = "4.0.0"
faccess = "0.2.4"
fslock = "0.2.1"
indoc = "1.0.8"
rm_rf = "0.6.2"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde_yaml = "0.9.16"
tempfile = "3.3.0"
cfgv = { path = "cfgv" }
cfgv-derive = { path = "cfgv-derive" }
pre-commit-rs-derive = { path = "pre-commit-rs-derive" }
pathdiff = "0.2.1"
gix = "0.38.0"
bstr = "1.3.0"
